ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:doctype: book
:toc: macro
:imagesdir: images
:toclevels: 5
:toc-title: Inhaltsverzeichnis
:numbered:

toc::[]

= KIM - Kommunikation im Medizinwesen

image:gematik_logo.svg[width=70%]

image:https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgematik%2Fapi-kim%2Fmain%2Fsrc%2Fopenapi%2FAccountManager.yaml&query=%24.info.version&style=plastic&logo=openapiinitiative&logoColor=green&label=AccountManager&color=green[link="src/openapi/AccountManager.yaml"]
image:https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgematik%2Fapi-kim%2Fmain%2Fsrc%2Fopenapi%2FAttachmentService.yaml&query=%24.info.version&style=plastic&logo=openapiinitiative&logoColor=green&label=AttachmentService&color=green[link="src/openapi/attachmentService.yaml"]
image:https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgematik%2Fapi-kim%2Fmain%2Fsrc%2Fopenapi%2FAccountLimit.yaml&query=%24.info.version&style=plastic&logo=openapiinitiative&logoColor=green&label=AccountLimit&color=green[link="src/openapi/AccountLimit.yaml"]
image:https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgematik%2Fapi-kim%2Fmain%2Fsrc%2Fopenapi%2FServiceInformation.yaml&query=%24.info.version&style=plastic&logo=openapiinitiative&logoColor=green&label=ServiceInformation&color=green[link="src/openapi/ServiceInformation.yaml"]
image:https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgematik%2Fapi-kim%2Fmain%2Fsrc%2Fopenapi%2FCommonSchemas.yaml&query=%24.info.version&style=plastic&logo=openapiinitiative&logoColor=green&label=CommonSchemas&color=green[link="src/openapi/CommonSchemas.yaml"]

== Inhalte & Zielgruppe

. *Für Hersteller Primärsysteme*
.. link:docs/Primaersystem.adoc[*Implementierungsleitfaden KIM für Primärsysteme*] zur Integration und geeigneten Nutzung von KIM in Primärsystemen
. *Für link:https://fachportal.gematik.de/anwendungen/kommunikation-im-medizinwesen[Hersteller von KIM-Produkten]*
.. link:src/openapi/[*OpenAPI Spezifikationen von Schnittstellen am KIM Fachdienst*], zur Implementierung von Schnittstellen im KIM Fachdienst, sowie Anbindung des KIM-Clientmodul an diese Schnittstellen

=== Geltungsbereich ===
Die in diesem Dokument formulierten Anforderungen sind informativ für Primärsysteme, die am Produktivbetrieb der Telematikinfrastruktur (TI) teilnehmen. Der Gültigkeitszeitraum der vorliegenden Version und deren Anwendung in Zulassungsverfahren wird durch die gematik GmbH in gesonderten Dokumenten (z. B. gemPTV_ATV_Festlegungen, Produkttypsteckbrief, Leistungsbeschreibung) festgelegt und bekannt gegeben.

== Systemarchitektur

KIM (vormals: KOM-LE) ermöglicht den sicheren elektronischen Datenaustausch zwischen registrierten, authentifizierten Nutzern der Telematikinfrastruktur (TI). KIM ermöglicht geschützten Versand der behandlungs-, therapie- und abrechnungsrelevanten Daten wie Arztbriefe, Befunde oder Abrechnungen. +

Das folgende Schaubild zeigt die direkt am Versand um Empfang einer KIM-E-Mail-Nachricht beteiligten TI-Komponenten (TI-Zugang = TI-Konnektor + VPN-Zugangsdienst oder TI-Gateway/HSK).

++++
<p align="center">
  <img width="90%" src=images/csm_KIM_Nachrichtenversand_und_Empfang_gematik_mitTIZugang__1__242ea5444f.png>
</p>
++++

== Querverweis zu Dokumenten der gematik ==
Generell wird *EMPFHOLEN*, dass mindestens die folgenden Dokumente der gematik, in ihrer Gesamtheit gelesen werden, um ein umfassendes Verständnis der Anforderungen, Abhängigkeiten und Spezifikationen zu erhalten. Ein Hersteller einer Clientanwendung muss Kenntnis von Eigenschaften des Services haben, den die Clientanwendung nutzen soll. Im Folgenden sind die wichtigsten Dokumente aufgelistet, die sich mit KIM beschäftigen, sowie deren Zielgruppen:
|===
|*Dokument* | *Name* | *Zielgruppe* 
|link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/[*gemSpec_CM_KOMLE*] | Spezifikation KOM-LE/KIM Clientmodul | Hersteller KIM-Produkte
|link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_FD_KOMLE/latest/[*gemSpec_FD_KOMLE*] | Spezifikation KOM-LE/KIM Fachdienst | Hersteller KIM-Produkte
|link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_VZD/latest/[*gemSpec_VZD*] | SpezifikationVerzeichnisdienst | Hersteller von Primärsystemen; Hersteller KIM-Produkte
|link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_Kon/latest/[*gemSpec_Kon*] | Spezifikation Konnektor | Hersteller von Primärsystemen; Hersteller KIM-Produkte
|link:https://fachportal.gematik.de/test-und-serviceprodukte/dienstkennung-kim-kom-le[*Dienstkennung KIM (KOM-LE)*] | Die Dienstkennungen für die Anwendung Kommunikation im Medizinwesen als Übersicht | Hersteller von Primärsystemen
|link:docs/Primaersystem.adoc[*Implementierungsleitfaden KIM für Primärsysteme*] | Implementierungsleitfaden KIM für Primärsysteme | Hersteller von Primärsystemen
|link:https://gemspec.gematik.de/docs/gemILF/gemILF_PS/latest/[*Implementierungsleitfaden Primärsysteme – Telematikinfrastruktur (TI)*] | Basis-Implementierungsleitfaden für Primärsysteme | Hersteller von Primärsystemen
|===

== License

Copyright 2026 gematik GmbH

Apache License, Version 2.0

See the link:LICENSE[LICENSE] for the specific language governing permissions and limitations under the License.

== Additional Notes and Disclaimer from gematik GmbH

1. Copyright notice: Each published work result is accompanied by an explicit statement of the license conditions for use. These are regularly typical conditions in connection with open source or free software. Programs described/provided/linked here are free software, unless otherwise stated.
2. Permission notice: Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions::
    1. The copyright notice (Item 1) and the permission notice (Item 2) shall be included in all copies or substantial portions of the Software.
    2. The software is provided "as is" without warranty of any kind, either express or implied, including, but not limited to, the warranties of fitness for a particular purpose, merchantability, and/or non-infringement. The authors or copyright holders shall not be liable in any manner whatsoever for any damages or other claims arising from, out of or in connection with the software or the use or other dealings with the software, whether in an action of contract, tort, or otherwise.
    3. The software is the result of research and development activities, therefore not necessarily quality assured and without the character of a liable product. For this reason, gematik does not provide any support or other user assistance (unless otherwise stated in individual cases and without justification of a legal obligation). Furthermore, there is no claim to further development and adaptation of the results to a more current state of the art.
3. Gematik may remove published results temporarily or permanently from the place of publication at any time without prior notice or justification.
4. Please note: Parts of this code may have been generated using AI-supported technology.’ Please take this into account, especially when troubleshooting, for security analyses and possible adjustments.
