:imagesdir: ./images

image:gematik_logo.svg[width=70%]


== KIM 1.5.3 Release Notes

=== Neu
- Das Feature Anwendungskennzeichen wurde in der gemSpec_CM_KOMLE und in der gemSpec_FD_KOMLE spezifiziert. Das Clientmodul ermöglicht die Administration über den Administrationsmodul und der Account Manager realisiert die Eintragung in den VZD.
- Anforderungen zum Einbringen der Anwendungskennung am Clientmodule sind erstellt (A_23713)
- Anforderungen zur Einbringung der Anwendungskennung durch den KIM Fachdienst in den VZD sind erstellt (A_23718, A_23722)
- Anforderungen für die Einbringung der Anwendungskennzeichen für den Verzeichnisdienst sind erstellt.
- Anforderungen für das Reporting der neuen X-KIM-Header wurden erstellt (neu Clientmodul: A_23737, Fachdienst: A_23746, A_23748). Für das Betriebsdatenreporting wurde ein Report erstellt.
- Am neuen Interface I_ServiceInformation wurde eine Passwort Policy in der Operation getServiceInformation beschrieben und kann dort abgefragt werden (A_23753, A_23754).
- A_23541 wurde erstellt. Wenn im Benutzernamen die IP-Adresse und der Port angegeben sind, dann hat dies Vorrang vor DNS-SD.
- Neue Anforderung erstellt A_23554 - "Weiterleitung MAIL FROM - SIZE-Parameter".
- Anforderung "A_23468 - Übermittlung der KAS-Datenmenge" wurde erstellt
- Neues Kapitel (6. Fehlernachrichten) in Primärsystem Leitfaden zu KIM auf gitHub
- Ein neues Headerelement X-KIM-Support wurde in Github für Primärsysteme definiert.

=== Geändert
- Anforderungen zum cachen wurden präzisiert, Konfigurationsparameter wurden erweitert (A_22348, A_22416-01, A_22340-01, KOM-LE-A_2026-01, KOM-LE-A_2061-01).
- AttachmentServices.yaml wurde erweitert, Tabelle 4: Operationen vom KAS wurde ergänzt (A_19375-05 - KAS – Implementierung der Schnittstelle).
- Bezüglich des Header "Expires" wurde der Text der Anforderung mit dem Hinweis auf RFC4021 ergänzt (A_22417-01).
- Das JWT zur Authentisierung am Account Manager verwendet nun die Attribute iat und exp anstatt nbf. Die Gültigkeitsdauer wurde auf 6 Stunden festgelegt (KOM-LE-A_2187-05).
- Das Prüfverfahren "Produkttest" wurde für KOM-LE-A_2304 entfernt.
- Die Anforderungen A_20189-02 und A_21389 wurden von der Clientmodul- in die Fachdienst-Spezifikation verschoben.
- Es wurde ein Hinweistext unter die Anforderung A_21387-03 platziert, dass eine Aktualisierung bei Verwendung eines HBA erst bei einem Mailabruf erfolgen kann, da der POP3 Benutzername die benötigte userID bereitstellt.
- Die KIM-Version 1.5 kann jetzt um ein optionales "+" erweitert sein. Verweise auf die gematik Dokumente und OpenAPI Definitionen wurden aktualisiert.
- Passwortschutz der PKCS#12 Datei ist nun optional (A_19468-03)
- Prüfverfahren "Produkttest" wurde für KOM-LE-A_2091-01 zugewiesen
- Prüfverfahren wurde für GS-A_4864 auf Herstellererklärung geändert
- GS-A_5138-02 "Performance – KOM-LE-Fachdienst – TLS-Verbindungsaufbau unter Last" wurde geändert.
- A_20127-01 "Performance - KOM-LE-Fachdienst – Spitzenlastvorgaben für den KAS" wurde geändert.
- KOM-LE-A_2187-05 geändert; Abhängigkeit für createCert vom VZD-Eintrag wurde entfernt. Der Aufbau des Json-Web-Token wurde geändert.
- Die Anforderung "KOM-LE-A_2187-05 - Authentifizierung des KOM-LE-Teilnehmers über AUT-Zertifikat am AccountManager" wurde geändert, so dass die Aufruf getAccount keinen Abgleich mit dem VZD benötigt.
- Eine Bildungsregel zur Ermittlung der HTTP Endpunkte wurde festgelegt (siehe Anforderung "A_19523 - Service-Discovery Administrationsmodul").
- Die Anforderung "KOM-LE-A_2179-02 - Vermerk in der Nachricht bei erfolgreicher Entschlüsselung" wurde überarbeitet, der separate Fehlertext wurde entfernt, X-KIM-DecryptionResult (ID 00) wird gesetzt.
- Anpassung der AttachementService.yaml Operation addAttachment (required true für Content-Length und Content-Disposition; A_22427-01)
- Anforderung A_19385-03 wurde bzgl. Karenzzeit erweitert,
- Anforderung A_19370-05 bzgl. dem unterschiedlichen Verhalten bei Fehlern angepasst.
- Anpassung der AttachmentService.yaml ist erfolgt, neues Header-Element X-KIM-KAS-Size wurde definiert: A_23467 - Übermittlung der KAS-Datenmenge
- Die neue Variante 1.5+ wurde in die Spezifikationen aufgenommen und als weitere mögliche Option genannt.
- Die Anforderung KOM-LE-A_2136 wurde auf Herstellererklärung geändert
- Präzisierung Kapitel "3.7 Administrationsmodul"; falsche Passage in Topic 4 gestrichen.
- Operation add_attachement (AttachmentService.yaml) wurde bei der Description ergänzt: Pro Form-Part wird genau eine Adresse spezifiziert und der Form-Part wird mehrfach angegeben (exploded=true)
- KOM-LE-A_2176-01 - Prüfen auf gültiges ENC-Zertifikat für den Empfänger im RCPT-Kommando" wurde geändert. Kein Abbruch wenn ein Empfänger ohne Zertifikat vorhanden.
- Anforderung KOM-LE-A_2167-05 "Sperrung des Accounts" wurde präzisiert.
- Anforderung A_19356-07 wurde verständlicher formuliert und ein Hinweis zum Content-Transfer-Encoding: base64 ergänzt.
- Die Anforderung KOM-LE-A_2135-01 wurde auf Herstellererklärung geändert
- A_19524-02 - Anforderung Verwaltung Resource Records Typs für Service Discovery, KIM" wurde präzisiert, feste Vorgabe für die Ports zw. den FD
- A_19378-02 - KAS - prüfen der Größe der verschlüsselten E-Mail-Daten" mit Hinweis auf Quota erweitert
- Anforderung A_22420-01 auf serverseitige Authentisierung geändert
- Tab_Fehlercodes_KOMLE-Clientmodule" mit neuen Fehlercodes (4018 + 4019) erweitert, Afo A_20650-06 neuer Index
- Beispiele in Kapitel "3.4.4.2.1 Entschlüsselung" wurden angepasst
- Tab_Konfig_Parameter Konfigurationsparameter Fachdienst KOM-LE wurde erweitert: "Löschfrist von Nachrichten nach der endgültigen Deregistrierung"; KOM-LE-A_2139-03 Konfiguration Fachdienst (neuer Index)
- Nachweis der Anforderungen KOM-LE-A_2184 wurde auf Herstellererklärung geändert.
- Nachweis der Anforderungen A_19454 und A_19455 wurde auf Herstellererklärung geändert.
- Die Schnittstelle I_AccountManager_Service wurde überarbeitet. Nicht schreibbare Attribute wurden aus setAccount entfernt.
- Die Message-ID wurde in allen Beispielen ergänzt.

=== Gelöscht
- Die Protokollierung von Performance Daten im Clientmodul wurde entfernt (geändert: KOM-LE-A_2079-01, gelöscht: KOM-LE-A_2084, KOM-LE-A_2088, KOM-LE-A_2089).
- GS-A_5136 "Performance – KOM-LE-Clientmodul – Bearbeitungszeit unter Last" wurde gestrichen.
- A_20130 "Performance - KOM-LE-Fachdienst - TLS Kanal KAS" wurde gelöscht.

Notes: Since April 2021 KIM is no longer a part of a gematik document release. Starting with KIM v1.5.1 it will be develop in a separate branch (see also https://fachportal.gematik.de/anwendungen/kommunikation-im-medizinwesen).

== KIM v1.5.2-1 - Release Notes
New feature
- added new operation to revoke deregistration to I_AccountManager_Service in v2.3.0 (see [I_AccountManager_Service](https://github.com/gematik/api-kim/blob/KIM-Hotfix-1.5.2/src/openapi/AccountManager.yaml) for more details)
- added new integrity checks to ensure correct setting of the from header in an e-mail
- added an example for processing of an email that needs to be stored at the kas (see [E-Mail Verarbeitung](https://github.com/gematik/api-kim/blob/KIM-Hotfix-1.5.2/docs/Email_Verarbeitung.adoc) for more details)

Changes
- change behavior for big attachments (see [Umgang mit großen Anhängen](https://github.com/gematik/api-kim/blob/KIM-Hotfix-1.5.2/docs/KIM_API.adoc#umgang-mit-gro%C3%9Fen-anh%C3%A4ngen) for more details)
- I_AccountManager_Service added some additional response codes
- updated I_Attachment_Service to v2.3.0 based on some changes on response codes(see [I_Attachment_Service](https://github.com/gematik/api-kim/blob/KIM-Hotfix-1.5.2/src/openapi/AttachmentService.yaml) for more details)
- updated I_AccountLimit_Servic to 1.1.0 based on setting a minimum value for maxMailSize(see [I_AccountLimit_Service](https://github.com/gematik/api-kim/blob/KIM-Hotfix-1.5.2/src/openapi/AccountLimit.yaml) for more details)
- removed I_Directory_Application_Maintenance from this repo and replaced references to the github repository of the vzd
- replaced sequence diagrams with plantuml based ones
- updated json schema for kim attachment data structure

== KIM v1.5.2 - Release Notes

New feature
- added new interface I_AccountLimit_Service (see [I_AccountLimit_Service](https://github.com/gematik/api-kim/blob/master/src/openapi/AccountLimit.yaml) for more details)
- added description of the interface: I_AccountLimit_Service in document "KIM_API.adoc"
- added new chapter AV-Service in implementation guideline for PS in document "Primaersystem.adoc"
- added X-KIM-Sendersystem Header Element in implementation guideline for PS in document "Primaersystem.adoc"

Changes
- updated I_AccountManager_Service to v2.2.0 (see [I_AccountManager_Service](https://github.com/gematik/api-kim/blob/master/src/openapi/AccountManager.yaml) for more details)
- updated I_Attachment_Service to v2.2.0 (see [I_Attachment_Service](https://github.com/gematik/api-kim/blob/master/src/openapi/AttachmentService.yaml) for more details)
- updated I_Directory_Application_Maintenance to 1.1.2 (see [I_Directory_Application_Maintenance](https://github.com/gematik/api-kim/blob/master/src/openapi/DirectoryApplicationMaintenance.yaml) for more details)
- refactored the API in document "KIM_API.adoc"
- refactored the descriptions of the interfaces in document "Fachdienst.adoc"
- updated the description of VZD in document "Verzeichnisdienst.adoc"
- updated the overview of KIM use cases in document "Anwendungsfaelle.adoc"
- updated examples of interface releases in URL in document "Versionierung.adoc"
- added description of the interface I_AccountLimit_Service in document "Authentisierung.adoc"
- updated SMTP/POP3-Benutzername in implementation guideline for PS in document "Primaersystem.adoc"
- refactored startpage in document "Readme.md"

== KIM v1.5.1 - Release Notes

New feature
- added support for Multi-Konnektor environments
- updated operations for registration process
- added new operations for user administration
- added new operations for out of office messages
- added new operations to port an TelematikID to new mail address
- added new interface DiretoryApplicationMaintenance v1.0.0
- added JSON-Web-Token for authentication
- added HTTP-Auth for uploading files to KAS

Changes
- updated I_AccountManager_Service to v2.0.0 (see [I_AccountManager_Service](https://github.com/gematik/api-kim/blob/master/src/openapi/AccountManager.yaml) for more details)
- updated I_Attachment_Service to v2.0.0 (see [I_Attachment_Service](https://github.com/gematik/api-kim/blob/master/src/openapi/AttachmentService.yaml) for more details)
- refactored the API of KAS and Account Manager in KIM_API.adoc
- refactored the overview of KIM use cases in Anwendungsfaelle.adoc
- refactored implementation guideline for PS in Primaersystem.adoc
- renamed parameter in Attachment_schema.json
- updated the description of VZD in Basisdienste.adoc
- added new section Authentisierung.adoc
- updated folder structure in Readme.md

== KIM v1.5

The specification KIM (KOM-LE) v1.5 is a part of gematik document release 4
(see also https://fachportal.gematik.de)

=== Document Release 4.0.1 - Hotfix 1

New feature
- added a KAS sample for multiple attachments

Changes
- updated I_AccountManager_Service to v1.2.0 (see [I_AccountManager_Service](https://github.com/gematik/api-kim/blob/master/src/openapi/AccountManager.yaml) for more details)
- updated I_Attachment_Service to v1.0.0 (see [I_Attachment_Service](https://github.com/gematik/api-kim/blob/master/src/openapi/AttachmentService.yaml) for more details)
- updated API for primary systems: restriction added for creating message IDs during message creation
- refactored the API of KAS and Account Manager in KIM_API.adoc
- replaced SMIME-Profil.zip with a new version to represent changes of header field Message-ID for both inner and outer email
- updated folder structure in Readme.md

=== Document Release 4.0.1

New features

- included implementation guideline for PS
- added subchapter versioning added
- added JSON schema for attachments
- added KIM S/SMIME sample messages

Changes

- added errorcode 413 in operation add_Attachment in I_Attachment_Service
- added parameter referenceID in I_AccountManager_Service
- updated folder structure in Readme.md

=== Document Release 4.0.0

- removed limiting of message sizes
- enabled the integration of the client module in the PVS (optional)
- embedded administration module for the configuration of the KIM account
- support for syntactic message categories
