ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:source-style: listing
endif::[]

ifndef::env-github[:source-style: source]

:imagesdir: images
= KIM 2.0 - Konzept

image:gematik_logo.svg[width=70%]

💡 Hier entstehen die ersten Lösungsideen für die Architektur von KIM 2.0. Es handelt sich um einen Arbeitstand der noch nicht intern vollständig abgestimmt ist und sich häufig ändern kann!

== Einführung

<Motivation>

<Ziele>

=== Einordnung des Dokuments

==== Zielsetzung

==== Zielgruppe

==== Abgrenzungen


== Lösungsstrategie

== Kontextabgrenzung

== Bausteinsicht

== Features

=== Authentisierung

==== Ausgangslage

Die Anwendung KIM ist für für Organisationen des Gesundheitswesens und deren Mitarbeiter sowie für Leistungserbringer (Personen) vorgesehen. Versicherte oder andere dürfen KIM nicht nutzen.
Daher ist es erforderlich, dass bei der Registrierung neuer KIM Accounts geprüft wird, ob der Nutzer berechtigt ist KIM zu nutzen. Wenn für bestehende Accounts die Nutzungsberechtigung nicht mehr gegeben ist, dann muss die Weiternutzung von KIM verhindert werden.


==== Anwendungsfall

==== Lösung und Architekturentscheidung

===== Laufzeitsicht

=== <Featurename>

==== Ausgangslage

==== Anwendungsfall

==== Lösung und Architekturentscheidung

===== Laufzeitsicht

== Querschnittliche Aspekte

=== Verteilungssicht

=== Testvorgehen

=== Betriebsmodell

=== Sicherheitsbetrachtung



== Abwärtskompatibilität




