ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:maildir: ../samples/Mails
:toc: macro
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=50%]

toc::[]

= E-Mail Handling
Diese Seite gibt einen Überblick über den Prozess der E-Mail Verarbeitung durch ein KIM-Clientmodul und einen beispielhaften Einblick in den Aufbau der E-Mail nach den jeweiligen Prozesschritten. Als Beispiel wird das Happy Day Szenario vom Versand einer Mail gewählt, die wegen ihrer Größe(20 MiB) einen Versand unter Einbezug des KIM-Attachment Service nach sich zieht. In die Client-Mail wurde ebenfalls die Verwendung eines modifizierten From Headers inkludiert. Das folgende Kapitel befasst sich mit dem Versandvorgang einer Clientmail, während der Empfangsvorgang dann in Kapitel <<Empfang einer E-Mail>> beschrieben wird.

== Versand einer E-Mail
Der Versand einer Mail startet, wenn von einem Client-System über SMTP eine MIME-Mail an das KIM-Clientmodul übergeben wird.

=== Empfangene Client-Mail
Das KOM-LE Clientmodul empfängt eine BASE64 kodierte Nachricht von einem Clientsystem(KIS, PVS, etc). Diese Mail verfügt über einen Anhang der eine Verarbeitung mit dem KIM-Attachment Service nötig macht und über den From Header wird versucht einen falschen Absender zu simulieren. Vom Clientsystem wurde keine X-KIM-Dienstkennung gesetzt.

.Client Mail
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Send_Client-Mail.txt[]
----
====

=== Geprüfte / um Header ergänzte Client-Mail
Das KOM-LE Clientmodul verarbeitet die Client-Mail und ergänzt die fehlende X-KIM-Dienstkennung. Es wird erkannt, dass die im *_From_* Header angegebene E-Mail Adresse nicht mit der Adresse des Senders aus dem *_SMTP FROM_* Kommando übereinstimmt und die Adresse im *_From_* Header entsprechend ersetzt.

.Mail mit Header und Senderkorrektur
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Send_processed_Client-Mail.txt[]
----
====

=== Mail nach dem KAS-Upload
Von der korrigierten(*_From_* Header) und um die Dienstkennung erweiterte Mail wird eine Kopie angelegt, die die Basis für die an den Fachdienst zu übermittelnde KOM-LE Nachricht bildet. Anschließen wir modifizierte Client-Mail signiert und verschlüsselt und das binäre Ergebnis und durch Aufruf der Methode addAttachment auf den KIM Attachment Service hochgeladen. Nach einem erfolgreichen Upload ersetzt das KOM-LE Modul den Body der KOM-LE Nachricht durch die KIM Attachment Datenstruktur.

.KOM-LE Nachricht mit Attachment Datenstruktur
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Send_processed_after_kas_upload.txt[]
----
====

=== Finale KOM-LE Mail
Der Body der KOM-LE Nachricht wird ebenfalls signiert und verschlüsselt. Anschließend wird die Nachricht per SMTP an den Fachdienst übertragen.

.signierte und verschlüsselte KOM-LE Nachricht
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Send_KOM-LE-Mail.txt[]
----
====

== Empfang einer E-Mail
Die folgenden Kapitel befassen sich mit der empfangenden Seite des KIM Clientmoduls, die nun die in den vorherigen Kapiteln zusammengestellte KOM-LE Mail vom Fachdienst abrufen und verarbeiten wird.

=== Empfangene KOM-LE Mail
Über POP3 ruft das KIM Clientmodul eine KOM-LE Nachricht beim Fachdienst ab.

.abgerufene KOM-LE Nachricht
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Receive_KOM-LE-Mail.txt[]
----
====

=== Entschlüsselte und geprüfte KOM-LE Nachricht
Das KIM-Clientmodul entschlüsselt die KOM-LE Nachricht und führt die Integritätsprüfungsschritte durch.
Nach der Entschlüsselung ist die KIM-Attachment Datenstruktur lesbar und die Informationen können genutzt werden, um die auf dem KAS abgelegte Client Mail abzurufen.

.entschlüsselte KOM-LE Mail
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Receive_decrypted_KOM-LE-Mail.txt[]
----
====

=== Mail nach dem KAS Download
Mit den Informationen aus der KIM-Attachment Datenstruktur wird die auf dem KAS abgelegte Mail heruntergeladen, entschlüsselt und die Signatur geprüft.

.vom KAS heruntergeladene entschlüsselte Nachricht
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Receive_kas_downloaded.txt[]
----
====

=== Finale Client-Mail
Die Header Felder der vom KAS heruntergeladenen Client-Mail werden mit den Header Feldern der KOM-LE Nachricht abgeglichen. In der Client-Mail werden die Header Felder (Received, Return Path, X-KIM Check Results) befüllt und Fehlertexte im Body ergänzt. Anschließend wird die Client-Mail Base64 codiert an das via POP3 abfragende Clientsystem ausgeliefert.

.Fertige Client Mail
[%collapsible]
====
[source,txt, linenums]
----
include::{maildir}/Receive_Client-Mail.txt[]
----
====

