:star: *

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:doctype: book
:docinfo: private
:toc: macro
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:numbered:

image:gematik_logo.svg[width=70%]





= Implementierungsleitfaden KIM für Primärsysteme (ILF KIM)

toc::[]


== Dokumentenhistorie

[cols="2,1,10",options="header",autowidth]
|===
|Datum |Version |Beschreibung

| bis Ende 2025
| link:https://github.com/gematik/api-kim/tree/ILF_1.0.0[1.0.0]
| Initiale Version & Maintenance-Änderungn sowie klarstellende Ergänzungen

|19.02.2026
|link:https://github.com/gematik/api-kim/tree/ILF_1.0.1[1.0.1]
| Korrekturen & Bereinigung von Inhalten zu aktuell entfallem der Anwendungskennzeichen und `appTags`

|===
== Normen und Spezifikationen
Anforderungen als Ausdruck normativer Festlegungen werden durch die dem [RFC2119] entsprechenden, in Großbuchstaben geschriebenen deutschen Schlüsselworte MUSS, DARF NICHT, SOLL, SOLL NICHT, KANN sowie ihrer Pluralformen gekennzeichnet.


== Abkürzungen und Begriffe
Generell sind Abkürzungen und Begriffe im link:https://fachportal.gematik.de/glossar[gematik Glossar] beschrieben. Die folgenden Abkürzungen und Begriffe sind für dieses Dokument wesentlich:

[cols="1,7"]
|===
|*ILF*
|Implementierungsleitfaden

|*KIM*
|Kommunikation im Medizinwesen

|*KAS*
|KIM Attachment Service - Speicherort großer KIM-E-Mail-Daten

|*CM*
|KIM-Clientmodul - dezentrale KIM-Komponente als Anwendungs-Proxy für Versand und Abruf von KIM-E-Mail-Nachrichten

|*VZD*
|Verzeichnisdienst

|*LE(I)*
|Leistungserbringer(-institution)

|*TI*
|Telematikinfrastruktur

|*VPN*
|Virtual-Private-Network

|*TSP*
|Trust-Service-Provider

|*PS/CS*
|Primärsystem/Clientsystem - Software, die Funktionen der TI-Plattform (KIM-Clientmodul, TI-Konnektor) nutzt

|*QES*
|Qualifizierte elektronische Signatur
|===


== Einleitung
Das sichere Übermittlungsverfahren KIM stellt Nutzern von Primärsystemen die Möglichkeit zur Verfügung, mit anderen KIM-Teilnehmern eine Ende-zu-Ende-gesicherte E-Mail-Kommunikation zu führen. Die *Ver-/Entschlüsselung* sowie die *Sicherstellung der Integrität von KIM-Nachrichten* (E-Mails) wird u.a. in Abhängigkeit zu Funktionen der dezentralen TI-Komponenten: TI-Konnektor, TI-Kartenterminals & Smartcards (SM-B und HBA) *durch das KIM-Clientmodul umgesetzt*. 

[width="100%",cols="1a"]
|===
|Dieser Leitfaden beschreibt die technische Basis zur Anbindung an sowie Nutzung von KIM durch *Primärsysteme*. +

*Abgrenzung* +

* Konkrete technische Festlegungen bzgl. KIM-Komponenten in der TI erfolgen durch link:https://gemspec.gematik.de/docs/gemSpec/[Spezifikationen] der gematik und beschreiben keine Primärsystem-Funktionalitäten. +

** Dazu zählen auch weitere Festlegungen aus bspw. [link:https://github.com/gematik/api-kim[api-kim github gematik]], die nicht explizit für die Audienz der Primärsysteme und Hersteller dieser ausgewiesen werden. +

* Spezifische Festlegungen bzgl. sog. "Fachverfahren" oder "payloads" link:https://fachportal.gematik.de/service/dienstkennung-kim-kom-le/[(i.d.R. Dienstkennungen KIM)] gelten als ergänzende Festlegungen. Sie sind *nicht* Bestandteil dieses Leitfadens.

*Empfehlung* +
Es wird empfohlen, diesen Leitfaden in Verbindung mit der link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/[Spezifikation des KIM-Clientmoduls] und des link:https://gemspec.gematik.de/docs/gemILF/gemILF_PS/latest/[Basis Implementierungsleitfadens für Primärsysteme] zu betrachten, da u.a. die Anforderungen an Schnittstellen und die Integration in ein Primärsystem darin bedingt, definiert sind.
|===


== Voraussetzungen
Für die Nutzung von KIM müssen die folgenden Punkte erfüllt sein:

[cols="1,9,5"]
|===
|Nr. |Voraussetzung |Verantwortlichkeit

|1
|Funktionsfähige, online TI-Anbindung des PS (TI-Konnektor, VPN, ...) ist vorhanden
|Nutzer, LE(I) oder Organisation, Dienstleister

|2
|Der Nutzer verfügt über eine freigeschaltete SM&lpar;C&rpar;-B (und ggf. einen freigeschalteten HBA)
|Nutzer, LE(I) oder Organisation

|3
|Die Basisdaten der TI-Identität (u.a. Anschrift, Zertifikate) des KIM-Nutzers sind im VZD eingetragen
|Kartenherausgeber und oder TSP im Auftrag von Verbänden, Kammern, ...

|4
|Installation, Konfiguration, Betrieb KIM-Clientmodul
|Nutzer, LE(I) oder Organisation, Primärsystemhersteller, Dienstleister

|5
|Registrierung bei einem KIM-Provider und Erhalt einer KIM-E-Mail-Adresse
|Nutzer, LE(I) oder Organisation

|6
|Die KIM-Fachdaten (u.a. KIM-E-Mail-Adresse) sind im VZD der TI-Identität des Nutzers angegeben
|KIM-Provider, automatisch bei Registrierung KIM-E-Mail-Adresse durch Nutzer

|7
|Funktionsfähige SMTP- & POP3 E-Mail-Client-Funktion im PS oder standalone E-Mail-Clientsoftware, sowie Konfiguration & Verbindung zu funktionsfähigem KIM-Clientmodul sowie ggf. TI-Konnektor
|Nutzer, LE(I) oder Organisation, Primärsystemhersteller, Dienstleister
|===

== Schnittstellen
Grundlage von KIM ist die E-Mail-basierte Kommunikation. Ein PS agiert als E-Mail-Client und das KIM-Clientmodul als E-Mail-Server. 
Zur Anbindung an KIM sind folgende Schnittstellen des KIM-Clientmoduls wesentlich:

* *SMTP-Schnittstelle* - Versand von KIM-E-Mail-Nachrichten +
* *POP3-Schnittstelle* - Abruf von KIM-E-Mail-Nachrichten +

Da die E-Mail-Kommunikation via KIM eine gerichtete Kommunikation zwischen identifiziertem Sender und Empfänger(n) ist, müssen zum Versand von E-Mails über KIM, die KIM-E-Mail-Adressen der Empfänger bekannt sein bzw. können über den VZD der TI ermittelt werden. Die KIM-E-Mail-Adressen können über die LDAP-Schnittstelle des TI-Konnektors (siehe dazu link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_Kon/latest/[Spezifikation LDAP-Proxy TI-Konnektor]) ermittelt werden:

* *LDAP-Schnittstelle* - Ermittlung und Abruf von Identitätsinformationen und KIM-E-Mail-Adressen aus dem VZD +

Die folgende Abbildung stellt die Abhängigkeitsbeziehungen zwischen den einzelnen Komponenten dar.

++++
<p align="center">
  <img width="70%" src=../images/Int_PS-KIM.svg>
</p>
++++

[width="100%",cols="1a"]
|===
|*Beachte* +

* Ein *PS hat keine direkte Verbindung* zum KIM-Fachdienst eines KIM-Providers oder dem VZD.
* Das KIM-Clientmodul und der vorgelagerte TI-Konnektor bauen direkte Verbindungen zu zentralen Diensten auf und agieren als Proxy für das PS.
|===


== Umsetzung

Dieses Kapitel beschreibt die wesentlichen, durch ein PS umzusetzenden Anwendungsfälle und daraus abgeleitetn technische Anforderungen der KIM-Nutzung. Die Implementierung eines KIM-fähigen E-Mail-Clients erfordert über die reine SMTP- & POP3-Anbindung hinaus auch eine robuste Umsetzung wesentlicher Basis-Funktionalitäten zur Nutzung und Bedienung eines E-Mail-Clients aus Sicht eines Nutzers sowie spezieller Festlegungen zu KIM.



=== KIM-E-Mails erstellen und versenden

==== Empfänger ermitteln

KIM-E-Mails können ausschließlich durch einen identifizierten Sender an identifizierte Empfänger übermittelt werden, die gemäß der <<Voraussetzungen>> KIM-E-Mail-Adresse(n) und dazu gehörende Verschlüsselungszertifikat(e) im VZD hinterlegt haben. Die Ermittlung dieser Informationen erfolgt über die LDAP-Schnittstelle des TI-Konnektors (LDAP-Proxy).

* *Verbindungsaufbau & Authentisierung* +

Für den Verbindungsaufbau zum TI-Konnektor bzw. LDAP-Proxy und dabei stattfindender Authentisierung gelten die Festlegungen gemäß link:https://gemspec.gematik.de/docs/gemILF/gemILF_PS/latest/#4.1.1.3[Implementierungsleitfaden Primärsysteme – Telematikinfrastruktur (TI)].

* *Suche im VZD* +

. Das PS MUSS Empfängerdaten über die LDAP-Schnittstelle des TI-Konnektors ermitteln, siehe dazu: link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_Kon/latest/#4.1.12[Spezifikation LDAP-Proxy TI-Konnektor] +
. Das PS muss die LDAP `search`-Operation gemäß `[RFC4511#4.5.1]`umsetzen. Diese Suche erfolgt anhand definierter Suchkriterien, den LDAP-Directory-Basisdatensatz-Attributen des VZD, siehe dazu:

** link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_VZD/latest[gemSpec_VZD#Tab_VZD_Datenbeschreibung]
** link:https://github.com/gematik/api-vzd/blob/main/docs/LDAP_Attribute.adoc[LDAP-VZD-Attribute]
** link:https://github.com/gematik/api-vzd/blob/main/docs/LDAP_Search.adoc[Beispiele LDAP-VZD-Suche]

. Beim Versand von E-Mail-Daten, die 15 MiB überschreiten, MUSS die durch einen Empfänger im VZD hinterlegte Freigabe zum Empfang großer E-Mails-Datenmengen berücksichtigt werden. Diese Angabe erfolgt durch ein *[+ (plus)]* hinter der KIM-Version im Attribut *"kimData"*. Ist diese Angabe nicht vorhanden, DARF die E-Mail NICHT an diesen Empfänger versendet werden. Dies MUSS dem Nutzer mit einer entsprechenden Fehlermeldung angezeigt werden.
. Daten im VZD können sich ändern. Das PS MUSS lokal gespeicherte KIM-Adress-Daten regelmäßig mit den Daten im VZD vergleichen und aktuell halten. Lokal gespeicherte KIM-E-Mail-Adresse sollen einmal täglich geprüft und ggf. aktualisiert werden.



==== Erstellung von KIM-E-Mails

Das PS ist verantwortlich für die Erstellung RFC-konformer MIME-Nachrichten und deren Übergabe per SMTP an das CM. Das PS trägt die Verantwortung für eine korrekte Nachrichtenstruktur sowie aller Pflicht-Angaben vor dem Versand.

. Das PS MUSS Nachrichten gemäß `[RFC5322]`, `[RFC2045]`, `[RFC2046]`, `[RFC2047]`, `[RFC4021]` erzeugen

. Generell MUSS UTF-8 als Standard-Kodierung verwendet werden +
.. Beachte u.a. `[RFC2047]`, betrifft bspw. explizit Header-Elemente sowie Dateinamen in Anhängen- Beispiel: Dateiname `Handbuch-ÄÜÖß.pdf`: `Content-Type: application/pdf; name="=?UTF-8?B?SGFuZGJ1Y2gtw4TDnMOWw58ucGRm?="` +

. Das Header-Element `Message-ID` ist für KIM-Nachrichten *obligatorisch*. Der Wert MUSS durch das PS gemäß *[RFC5322 §3.6.4]* eindeutig erzeugt werden, *darf nicht wiederverwendet werden* und darf *keine datenschutzrelevanten Informationen*, wie bspw. interne FQDNs oder personenbezogene Daten enthalten. Empfohlen wird die Verwendung einer UUID nach *[RFC4122]*: `Message-ID: <\550e8400-e29b-41d4-a716-446655440000@kim.local>` +

. Konversationsreferenzen, zur Möglichkeit einer korrekten Anzeigen von Konversationsverläufen  +
.. Beim Antworten auf KIM-E-Mail-Nachrichten MUSS das PS `In-Reply-To` mit der `Message-ID` der Ursprungsnachricht befüllen. +
.. Das Header-Element `References` KANN zur Verkettung des gesamten Konversationsverlaufes genutzt werden. Dies ermöglicht anderen KIM-Clients die korrekte Anzeige von Konversationsverläufen.

. Nachfolgende *Header-Elemente* MÜSSEN durch das PS gesetzt werde können *[Pflicht]*: +
.. Werte der Header-Elemente mit Vermerk *[REGEX]* müssen konform zu den regulären Ausdrücken unter folgendem Link sein (Sanitization): link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_Perf/latest/[gemSpec_Perf#A_23167-*]


[options="header",autowidth]
|===
|Header |Beschreibung / Verbindlichkeit / Format

|`From`, `To` ggf. `Cc`, `Date`, `Message-ID`
|*[Pflicht].* gemäß *[RFC5322]*

|`X-KIM-Sendersystem`
|*[Pflicht]*; *[REGEX]* Format: `<Systemname>;<Version>` — z.B. `MeinPVS;2.0.0`. Dient der allgemeinem Identifikation des PS-Herstellers.

|`X-KIM-Support`
|*[Pflicht]*; *[REGEX]* Support-E-Mail-Adresse des PS-Herstellers. Ermöglicht Kontaktaufnahme bei bspw. Fehleranalyse.

|`X-KIM-Dienstkennung`
|*[Pflicht]*; *[REGEX]* Kategorisierung der Nachricht. Ohne Angabe setzt das KIM CM den Standardwert. Kann auf der Empfängerseite für Abrufsteuerung sowie automatisierte Verarbeitung verwendet werden. Aktuelle Kennungen: link:https://fachportal.gematik.de/service/dienstkennung-kim-kom-le/[Dienstkennungen KIM - Fachportal gematik]

|`X-KIM-Middleware`
|*[REGEX]* Wird von einer zwischengeschalteten Middleware-Komponente gesetzt, sofern eine solche zwischen PS und KIM CM eingesetzt wird. Format: `<Middlewarename>;<Version>` — z.B. `MiddlewareXYZ;2.0.0`

|`X-TI-User-Agent`
|*[Pflicht]*; *[REGEX]* Übermittlung einer bei der gematik registrierten, eindeutigen Identifikators (client-id/product-id) des PS gemäß (link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_Perf/gemSpec_Perf_V2.75.0/#A_27784[A_27784-* - Senden eines User-Agents (Clientsysteme)])
|===


[.transparent-background]
****

.Beispiel einer vom PS erzeugten (KIM-)E-Mail-Nachricht
[%collapsible%open]
====
[source, txt, linenums]
----
Message-ID: <c37a9fe5-a4b2-222d-35ba-6358fa26e48b@gematik.kim.telematik-test>
Date: Fri, 9 Sep 2022 15:47:00 +0200
MIME-Version: 1.0
From: user.test15@gematik.kim.telematik-test
To: "user.test16"
 <user.test16@gematik.kim.telematik-test>,
Cc: allowed_recipient@gematik1.telematik-test
X-KIM-Dienstkennung: KIM-Mail;Default;V1.0
X-KIM-Sendersystem: meinPVS;2.0.0
X-KIM-Middleware: meinPVSMiddleware;2.0.0
X-KIM-Support: service@meinpvs.de
X-TI-User-Agent: MeinPvsFirma-gemApproved/2.0.0
Subject: KIM Testnachricht
Content-Type: multipart/mixed; boundary="----v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed"

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed
Content-Type: multipart/alternative; boundary="----v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative"

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative
Content-Type: text/plain; charset="UTF-8"

Dies ist die Text-Version (Alternative 1).

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative
Content-Type: text/html; charset="UTF-8"

<html><body><p>Dies ist die <b>HTML-Version</b> (Alternative 2).</p></body></html>

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative--

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed
Content-Type: application/pdf; name="datei.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="datei.pdf"

JVBERi0xLjQKJ... (Base64 kodierter Inhalt) ...

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed--

----
====
****

[width="100%",cols="1a"]
|===
|*Hinweise* +

*Signatur von Dokumenten* +
Dokumente, welche mit einer KIM-E-Mail-Nachricht, bspw. als Anhang, übertragen werden sollen, können oder müssen ggf. vorab mittels Funktionen des TI-Konnektors signiert werden (QES). Dies ist *nicht* Teil der KIM-Funktionalität.

*Größenprüfung vor dem Versand* +
Die 15-MiB-Grenze aus Abschnitt <<Empfänger ermitteln>> bezieht sich auf die *dekodierte* MIME-Message (ohne Kodierungs-Overhead). Da bspw. die Base64-Kodierung die Transportgröße um den Faktor ~1,37 erhöht, muss das PS die daraus resultierende Datenmenge, die an das KIM CM übermittelt werden würde als Größe bzgl. der in <<Empfänger ermitteln>> geforderten Prüfung zur Empfangsfähigkeit verwenden.
|===


==== Versand von KIM-E-Mails

[.transparent-background]
****
*Beispiel für typische SMTP-Sequenz PS → CM:*
----
PS → CM:  (TCP-Verbindungsaufbau, TLS-Handshake falls konfiguriert)
CM → PS:  220 <hostname> ESMTP
PS → CM:  EHLO <primärsystem-hostname>
CM → PS:  250-<hostname>
          250-SIZE 734003200
          250-AUTH LOGIN PLAIN
          250-8BITMIME
          250-ENHANCEDSTATUSCODES
          250 DSN
PS → CM:  AUTH PLAIN <base64-credentials>
CM → PS:  235 Authentication successful
PS → CM:  MAIL FROM:<absender@hrst_domain.kim.telematik>
PS → CM:  RCPT TO:<empfaenger@hrst_domain.kim.telematik> NOTIFY=SUCCESS,FAILURE
PS → CM:  DATA
CM → PS:  354 Start mail input
PS → CM:  <Nachrichteninhalt>
PS → CM:  <CRLF>.<CRLF>
CM → PS:  250 OK
PS → CM:  QUIT
CM → PS:  221 Bye
----
****

*Verbindungsaufbau*

. Die SMTP-Verbindung zum CM MUSS per SMTP, gemäß *[RFC5321]* erfolgen. +
. Timeouts für den Versandvorgang MÜSSEN, auch durch den Nutzer, einfach konfigurierbar sein. +
. Das PS MUSS Vorgaben gemäß Kapitel [<<Transportsicherung zwischen Primärsystem und KIM-Clientmodul>>] umsetzen +

*Authentisierung*

. Das PS MUSS SASL `PLAIN` und/oder `LOGIN` für die SMTP-Authentisierung gemäß *[RFC4616]*, *[RFC4954]* verwenden. +
. Das PS MUSS die Angabe des SMTP-Benutzernamen in KIM ermöglichen. +
.. Diesbezüglich gelten spezifische Festlegungen aus der Spezifikation des KIM-Clientmodul link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#3.3.2.2[gemSpec_CM_KOMLE#3.3.2.2]. Darin sind ebenfalls Beispiele für Benutzernamen aufgeführt.

[width="100%",cols="1a"]
|===
|*Beachte* +

* Die Parameter-Reihenfolge des SMTP-Benutzernamens untercheidet sich von der Reihenfolge im POP3-Benutzernamen. +

* Ist die versendende KIM-E-Mail-Adresse/KIM-Account einer HBA-Identität zugeordnet, MUSS eine `UserId` des TI-Konnektor-Aufrufskontextes im Benutzernamen angegeben werden. +

* Bei Integration in bestehende Mail-Systeme kann der Delimiter `:` zwischen Hostname und Port (z. B. `hrst_domain.kim.telematik:465`) zu Problemen führen. Das CM unterstützt alternative Delimitervarianten, sofern die semantische Abgrenzung der Bestandteile gemäß *[RFC1123, RFC2822]* erhalten bleibt.
|===

*Zustellbestätigungen -  Delivery Status Notification (DSN)* +

* Das PS KANN per `RCPT TO:<...> NOTIFY=SUCCESS,FAILURE,DELAY` DSN-Rückmeldungen gemäß *[RFC3461]* anfordern. +
** DSN-E-Mail-Nachrichten werden vom KIM-Fachdienst generiert und durch diesen an den Absender zurückgesendet.

*Lesebestätigung - Message Disposition Notification (MDN)* +

* Das PS KANN u.a. per `Disposition-Notification-To`-Header gemäß *[RFC8098]* eine Lesebestätigung vom empfangenden E-Mail-Client anfordern. +
** _Beachte_: Es kann nicht garantiert werden, dass der empfangende E-Mail-Client dem entsprechend, mit einer MDN darauf antwortet.

*Asynchrone Fehlernachrichten* +

* Versand-seitige Fehlernachrichten werden asynchron, automatisch als neue E-Mail durch das CM erzeugt und an die Absenderadresse gesendet. Erst beim nächsten POP3-Abruf durch das PS können diese sichtbar werden. 
** Das PS *MUSS* diese E-Mail-Fehlernachrichten anhand des `X-KIM-Fehlermeldung`-Headers erkennen, abrufen und anzeigen können.



=== KIM-E-Mails abrufen, anzeigen und verwalten

[.transparent-background]
****
*Beispiel für typische POP3-Sequenz PS → CM:*
----
PS → CM:  (TCP-Verbindungsaufbau, TLS-Handshake falls konfiguriert)
CM → PS:  +OK KIM POP3 ready
PS → CM:  CAPA
CM → PS:  +OK Capability list follows
          TOP
          USER
          SASL PLAIN
          UIDL
          .
PS → CM:  AUTH PLAIN <base64-credentials>
CM → PS:  +OK Logged in
PS → CM:  UIDL
CM → PS:  +OK
          1 <uid-nachricht-1>
          2 <uid-nachricht-2>
          .
PS → CM:  TOP 2 0
CM → PS:  +OK (Header von Nachricht 2)
PS → CM:  RETR 2
CM → PS:  +OK (vollständige Nachricht 2, entschlüsselt)
PS → CM:  QUIT
CM → PS:  +OK Goodbye
----
****

* Das PS *MUSS alle verfügbaren KIM-E-Mail-Nachrichten* über das CM abrufen. 

Getriggert vom PS, ruft das CM KIM-E-Mail-Nachrichten vom KIM-Fachdienst ab entschlüsselt, prüft diese und stellt sie dem PS über eine POP3-Schnittstelle in Klartext zur Verfügung. Das PS ist verantwortlich für den korrekten, robusten Abruf, die Verarbeitung, Speicherung und Verwaltung der E-Mail-Daten.

*Verbindungsaufbau*

. Die POP3-Verbindung zum CM MUSS per POP3, gemäß *[RFC1939]* mit Extensions gemäß *[RFC2449]* erfolgen +
. Timeouts für den Abrufvorgang MÜSSEN, auch durch den Nutzer, einfach konfigurierbar sein. +
. Das PS MUSS die Vorgaben gemäß Kapitel [<<Transportsicherung zwischen Primärsystem und KIM-Clientmodul>>] umsetzen +

*Authentisierung*

. Das PS MUSS für die POP3-Authentisierung `USER`+`PASS` gemäß *[RFC1939]* und/oder SASL `PLAIN` gemäß *[RFC4616]* verwenden +
. Das PS MUSS die Angabe des POP3-Benutzernamen in KIM ermöglichen. +
.. Diesbezüglich gelten spezifische Festlegungen aus der Spezifikation KIM-Clientmodul link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#3.4.2.2[gemSpec_CM_KOMLE#3.4.2.2]. Darin sind ebenfalls Beispiele für Benutzernamen aufgeführt.

[width="100%",cols="1a"]
|===
|*Beachte* +

* Die Parameter-Reihenfolge des POP3-Benutzernamens unterscheidet sich von der Reihenfolge im SMTP-Benutzernamen. +

* Ist die versendende KIM-E-Mail-Adresse/KIM-Account einer HBA-Identität zugeordnet, MUSS die `UserId`, identisch zum TI-Konnektor-Aufrufskontext, im POP3-Benutzernamen angegeben werden +

* Bei Integration in bestehende Mail-Systeme kann der Delimiter `:` zwischen Hostname und Port (z. B. `hrst_domain.kim.telematik:465`) zu Problemen führen. Das CM unterstützt alternative Delimitervarianten, sofern die semantische Abgrenzung der Bestandteile gemäß *[RFC1123, RFC2822]* erhalten bleibt.
|===

*POP3 UIDL-basierter Nachrichtenabruf* +

. Das PS *MUSS* `POP3 UIDL` nutzen, um ausschließlich *neue, bisher unbekannte KIM-E-Mail-Daten* abzurufen:

.. *`UIDL`:* Abruf aller Message-Nummern <MsgNr> und deren UIDs im Postfach. Anhand lokal gespeicherter UIDs können neue Nachrichten identifiziert werden
.. (optional) *`TOP <MsgNr> 0`:* Abruf der Header von neuen Nachrichten, ggf. für Vorschau, Verarbeitungssteuerung nutzen (`X-KIM-Dienstkennung`, `X-KIM-Fehlermeldung`, Größe, ...)
  ... Bereits bekannte Header-Informationen einer bekannten KIM-E-Mail-Nachrichten SOLLEN NICHT wiederholt abgerufen werden
  ... _Beachte:_ Das CM setzt den Parameter `<N>` des TOP-Kommandos, unabhängig vom übergebenen Wert, immer auf `0` [gemSpec_CM_KOMLE#KOM-LE-A_2041]. `TOP <MsgNr> 0` liefert ausschließlich den E-Mail-Header ohne Nachrichteninhalt.
.. *`RETR <MsgNr>`:* Abruf vollständiger KIM-E-Mail-Nachricht
  ... Bereits abgerufene KIM-E-Mail-Nachrichten DÜRFEN NICHT erneut abgerufen werden
.. *On-Demand-Abruf:* Das PS MUSS das manuelle Auslösen eines Nachrichtenabrufs, außerhalb konfigurierter Abrufintervalle, ermöglichen


==== Verarbeitung und Anzeige abgerufener KIM-E-Mails

. Das PS *MUSS alle verfügbaren KIM-E-Mail-Nachrichten abrufen*, auswerten und einem Nutzer anzeigen können +
.. Sofern eine E-Mail/MimeMessage mit `multipart/alternative` & `text/plain` (nur Text) als auch `text/html` (formatierter Text) MimeParts vorliegt, ist die Anzeige des formatierten Inhalts (`text/html`) zu bevorzugen, siehe dazu link:https://www.rfc-editor.org/rfc/rfc2387.html[RFC 2387]. +
. KIM-E-Mail-Daten MÜSSEN so gespeichert werden, dass gleiche Daten nicht wiederholt abgerufen werden, siehe `POP3 UIDL` +
.. *_Beachte_*: Hinweise zum (automatischen) Löschen von KIM-E-Mail-Daten, siehe Kapitel [<<Löschen von KIM-E-Mail-Nachrichten>>]. +
. Anhänge von KIM-E-Mail-Nachrichten MÜSSEN weitergenutzt bzw. -verarbeitet werden können. +
. Die Anforderung einer Lesebestätigung - *Message Disposition Notification (MDN)*, gemäß *[RFC8098]* muss erkannt, ausgewertet und ggf. dem Nutzer angezeigt werden. +
. Für Analysezwecke MÜSSEN *alle Header-Elemente* der KIM-E-Mail-Nachrichten angezeigt werden können. 
.. Es SOLLTE der gesamte Nachrichten-Quelle-Text (MIME-Tree) angezeigt werden. +

[.transparent-background]
****

.Beispiel abgerufene KIM-E-Mail-Nachrichten
[%collapsible%open]
====
[source,txt, linenums]
----
Received: from 10.62.0.13 (EHLO 192.163.162.20:64500) ([10.62.0.13])
          by mailserver.gematik.kim.telematik-test (SMTP Server ) with ESMTPA ID 54965859
          for <user.test16@gematik.kim.telematik-test>;
          Fri, 09 Sep 2022 15:50:05 +0200 (CEST)
Message-ID: <c37a9fe5-a4b2-222d-35ba-6358fa26e48b@gematik.kim.telematik-test>
Date: Fri, 9 Sep 2022 15:47:00 +0200
MIME-Version: 1.0
From: user.test15@gematik.kim.telematik-test
To: "user.test16"
 <user.test16@gematik.kim.telematik-test>,
Cc: allowed_recipient@gematik1.telematik-test
Return-Path: <user.test15@gematik.kim.telematik-test>
X-KIM-Dienstkennung: KIM-Mail;Default;V1.0
X-KIM-Sendersystem: meinPVS;2.0.0
X-KIM-Middleware: meinPVSMiddleware;2.0.0
X-KIM-Support: service@meinpvs.de
X-TI-User-Agent: MeinPvsFirma-gemApproved/2.0.0
X-KIM-DecryptionResult: 00
X-KIM-IntegrityCheckResult: 01
Subject: KIM Testnachricht
Content-Type: multipart/mixed; boundary="----v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed"

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed
Content-Type: multipart/alternative; boundary="----v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative"

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative
Content-Type: text/plain; charset="UTF-8"

Dies ist die Text-Version (Alternative 1).

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative
Content-Type: text/html; charset="UTF-8"

<html><body><p>Dies ist die <b>HTML-Version</b> (Alternative 2).</p></body></html>

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Alternative--

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed
Content-Type: application/pdf; name="datei.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="datei.pdf"

JVBERi0xLjQKJ... (Base64 kodierter Inhalt) ...

------v0Sp8vvZ1qGfAWh1MYiwrJ0W_Boundary_Mixed--
----
====
****

==== Auswertung X-KIM-Header empfangener Nachrichten +

Entschlüsselte Nachrichten enthalten spezifische X-KIM-Header, welche konkrete Statusaussagen bieten. 

. Das PS MUSS folgende X-KIM-Header auswerten, wenn diese vorhanden sind und dem Nutzer geeignet anzeigen können:

.. link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#KOM-LE-A_2046-02[`X-KIM-DecryptionResult`]: Ergebnis der Entschlüsselung

.. link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#3.4.4.2.2[`X-KIM-IntegrityCheckResult`]: Ergebnis der Integritätsprüfung

.. link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#A_20650-07[`X-KIM-Fehlermeldung`]: Fehlernachricht

.. (optional) link:https://fachportal.gematik.de/service/dienstkennung-kim-kom-le/[`X-KIM-Dienstkennung`]: Kategorisierung der Nachricht, z.B. `eEB`, `eRezept;Rezeptanforderung`, ...; *wichtig* für spezifische Verarbeitung, Kategorisierung, Anzeige, ... einer Nachricht

.. link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#A_28582[`X-KIM-Auth`] (SOLL NICHT als Abbruchkriterium verwendet werden): Ein JWT zur 
... Anzeige von Signatur-Informationen anhand des link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_PKI/latest/[AUT-Zertifikats] aus `x5c`-Claim 
... (optional) Zertifikatsprüfung anhand des link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_PKI/latest/[AUT-Zertifikats] aus `x5c`-Claim 
... (optional) Absenderverifikation über `sub`-Claim (Absenderadresse)
.. Das PS MUSS Header-Felder, die in empfangenen Nachrichten mit unbekanntem `X-KIM-*` vorkommen, nicht auswerten, jedoch anzeigen können.


[width="100%",cols="1a"]
|===
|*Beachte* +

Das PS MUSS dem Nutzer Nachrichten mit `X-KIM-IntegrityCheckResult` und einem Wert ungleich `01` *mit deutlicher Warnung* präsentieren. Den Inhalten dieser Nachrichten darf nicht vertraut werden.
|===

==== Löschen von KIM-E-Mail-Nachrichten +

* Da eine KIM-E-Mail-Adresse (Postfach) an mehreren Arbeitsplätzen genutzt und damit KIM-E-Mail-Nachrichten abgerufen werden können, SOLLEN Nachrichten per `POP3 DELE` vom Server erst dann gelöscht werden, wenn diese gesichert nicht erneut abgerufen werden müssen. +
* Das PS MUSS dem Nutzer das manuelle Löschen von Nachrichten einfach ermöglichen (UI/UX). +

[width="100%",cols="1a"]
|===
|*Beachte* +

KIM-E-Mail-Nachrichten werden nach einer festgelegten Zeitspanne (default 90 Tage) automatisch durch den KIM-Fachdienst/-Provider gelöscht. 
|===

=== Fehlerzustände 

. Sämtliche Fehlerzustände MÜSSEN vom PS generell erkannt und dem Nutzer geeignet angezeigt werden können, dazu zählen u.a.:
.. Statuscodes/-rückmeldungen aus der Protokoll-Kommunikation SMTP, gemäß *[RFC5321 & RFC3463]* und POP3, gemäß *[RFC1939]* 
.. KIM-E-Mail-Fehlernachrichten sowie DSNs gemäß *[RFC3461 - RFC3463]*
.. Informationen aus KIM-Header-Elementen
... link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#KOM-LE-A_2046-02[`X-KIM-DecryptionResult`] → Ergebnis der Entschlüsselung
... link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#3.4.4.2.2[`X-KIM-IntegrityCheckResult`]: → Ergebnis der Integritätsprüfung
... link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#A_20650-07[`X-KIM-Fehlermeldung`]  →  Fehlernachricht

[width="100%",cols="1a"]
|===
|*Beachte* +

* Beschränkungen auf bestimmte Fehlercodes o.ä. sind zu vermeiden. Eine allgemeine Prüfung auf Fehlerzustände, wie z.B. das Vorhandensein von `X-KIM-Fehlermeldung`-Headern ist zu bevorzugen, da Klassifikation und Bedeutung von Fehlerzuständen in der Fehleranalyse relevant sind bzw. sich diese ändern können (Erweiterungen neue Fehlertypen, -codes, ...). +

* Weitere Fehlerzustände/-ursachen, die das PS kennt oder selbst verursacht sind analog zu betrachten.
|===

== Anforderungen an Benutzeroberfläche und Benutzerinteraktion eines Primärsystems

Dieses Kapitel beschreibt die grundlegenden Anforderungen an die Benutzeroberfläche und Benutzerinteraktion eines Primärsystems zur Nutzung von KIM.
Dies setzt voraus, dass das PS über eine Benutzeroberfläche mit Nutzern interagiert.

. Die Benutzeroberfläche des PS MUSS es Nutzern ermöglichen, KIM-E-Mails zu erstellen, zu versenden, zu empfangen, anzuzeigen, zu verwalten, Fehler zu erkennen und notwendige Konfigurationen vorzunehmen. +
. Das PS MUSS erkennbar mindestens die folgenden Funktionsaspekte in seiner Benutzeroberfläche für Benutzerinteraktionen bereitstellen.

*Bereiche der E-Mail-Verwaltung*

. Sinngemäß mindestens die Bereiche: `Posteingang`, `Gesendet`, `Entwürfe`, `Papierkorb` 

*Nachrichtenliste* +

. Auslistung zur Übersicht der KIM-E-Mail-Nachrichten in einem ausgewählten Bereich +
. Listenelemente müssen mindestens folgende Informationen ausweisen: `Absender`, `Betreff`, `Datum`, `Status (gelesen / ungelesen)` +
. Klassifikationen, bspw. anhand von `X-KIM-Dienstkennung`, werden empfohlen und ermöglichen u.a. Filterung, Sortierung, (farbliche) Hervorhebung, ... +

*Konfiguration & Einstellungen* 

. Bereich zur Konfiguration von KIM, der mindestens die Angabe und Verwaltung folgender Parameter ermöglicht: +
.. KIM-Anmeldedaten +
.. Timeout-Einstellung +
.. Abruf-Intervalle +
.. Verbindungs-Einstellungen (Endpunkte, TLS, Zertifikate) +

*Erstellung von KIM-E-Mail-Nachrichten*

. Das PS muss eine Benutzeroberfläche zur Erstellung und Bearbeitung von KIM-E-Mail-Nachrichten, mit folgenden Funktionen bereitstellen:  +
.. Eingabefelder/-bereiche für `Empfänger (To, Cc)`, `Betreff (subject)`, Nachrichtentext +
.. Möglichkeit zum Hinzufügen von Datein als Anhänge +
.. Möglichkeit zum Speichern einer Nachricht als Entwurf +
.. Schaltfläche zum Versenden der Nachricht +
. Suche im VZD anhand kombinierbarer Suchkriterien, siehe dazu <<Empfänger ermitteln>>
.. Die Suchkriterien und Ergebnisse der Suche MÜSSEN in einer für den Nutzer verständlichen Weise dargestellt werden.
.. Bei mehreren Suchergebnissen MÜSSEN die Ergebnisinformationen dem Nutzer vollständig zur Auswahl angezeigt werden.


*Versand von KIM-E-Mail-Nachrichten*

. Auslösen des Versands über eine eindeutige Benutzeraktion (z. B. „Senden“-Button) +
. Anzeige des Versandstatus +
. Anzeige von Fehlermeldungen aus Versandprozess +
. Speicherung erfolgreich versendeter Nachrichten im Ordner „Gesendet“ +
. Versandprozess muss für Nutzer nachvollziehbar (z. B. durch Fortschrittsanzeige, Statusmeldungen) und protokolliert sein +

*Empfang von KIM-E-Mail-Nachrichten*

. Alle verfügbaren, neuen KIM-E-Mail-Nachrichten müssen abgerufen werden können, siehe dazu Kapitel <<POP3 Abruf und Verwaltung von KIM-E-Mails>>. +
. Der Abruf von KIM-E-Mail-Nachrichten muss manuell, durch den Nutzer auslösbar sein +
. Anzeige neuer Nachrichten im entsprechenden Bereich +
. Kennzeichnung ungelesener sowie gelesener Nachrichten +
. Aktualisierung der Nachrichtenliste beim Abrufen neuer KIM-E-Mail-Nachrichten +

*Nachrichtenansicht*

. Alle abgerufenen KIM-E-Mail-Nachrichten müsssen angezeigt werden können +
. Die Benutzeroberfläche muss folgende Informationen darstellen: `Absender`, `Empfänger`, `Betreff`, `Datum`, `Nachrichtentext` +
. Anhänge müssen weiterverarbeitet werden können (öffnen, herunterladen, speichern, ...) +
. Bedarfsgerechte Möglichkeit zur Anzeige *sämtlicher Header-Elemente einer KIM-E-Mail-Nachricht*, (optional) Anzeige des gesamten Nachrichten-Quelletextes +
. "Antworten" & "Weiterleiten" einer KIM-E-Mail-Nachricht MUSS funktional vorhanden und auswählbar sein
. Dedizierte Anzeige relevanter KIM-Eigenschaften +
.. Anzeige, dass es eine KIM-E-Mail-Nachricht ist. Abgrenzung von anderen E-Mails, Nachrichten anderer Kommunikationsmodalitäten +
.. Anzeige von Information aus KIM-spezifische Header `X-KIM-Auth` (Authentizitätsinformationen), wenn vorhanden +

*Verwaltung von KIM-E-Mail-Nachrichten*

. Suchen von Nachrichten
. Löschen von Nachrichten
. Markieren von Nachrichten als gelesen oder ungelesen
. Sortieren einer Nachrichtenliste nach:
.. Datum
.. Absender

*Status und Rückmeldung Benutzerinteraktion & Zustände*

. Eindeutige Rückmeldungen bei Benutzeraktionen (z. B. Versand, Fehler) +
. Fehlerzustände, wie Fehlernachrichten, Statuscodes aus Versand und Empfang müssen erkannt und dem Nutzer angezeigt werden +



== Transportsicherung zwischen Primärsystem und KIM-Clientmodul

Das CM agiert als TLS-Server gegenüber dem Primärsystem (TLS-Client). Die entsprechenden Anforderungen an das CM sind hierfür maßgeblich (siehe link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#4.1.2[`Transportsicherung zwischen Clientsystem und Clientmodul - gemSpec_CM_KOMLE:4.1.2`]).

=== TLS-Pflicht

* Das PS MUSS *TLS* für SMTP- und POP3-Verbindungen zum CM nutzen.

=== TLS-Zertifikate des Clientmoduls

. Das CM bezieht sein TLS-Server-Zertifikat automatisch bei der ersten Registrierung an seinem KIM Fachdienst. Allerdigs ist es möglich sowohl ein selbstsigniertes als auch ein importiertes TLS-Server-Zertifikat in eigener administrativer Verantwortung zu verwenden.
.. Das PS MUSS mit diesem Szenario umgehen können, z. B. durch regelmäßige Überprüfung des TLS-Server-Zertifikats und erneutem Import sowie erneuter Vertrauensherstellung bei Änderung. +
. Es sind die zulässigen kryptographische Verfahren gemäß link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#A_25232-01][`TLS-Zertifikate für die Authentisierung gegenüber Clientsystemen - gemSpec_CM_KOMLE:A_25232-*`]] zu beachten.
. Das PS MUSS in der Lage sein, (selbstsignierte) TLS-Zertifikate des CM zu importieren und zu nutzen, für bspw.:
.. Import und Nutzung eines Client-Zertifikats (siehe <<TLS-Client-Authentisierung>>)
.. Prüfungen wie bspw. fingerprint-basierte Vergleich
. _Beachte_: Prüfung gegen Root/Sub-CAs (bspw. des OS) reichen i.d.R. nicht aus. 


[width="100%",cols="1a"]
|===
|*Beachte* +

* Eine standardmäßige Zertifikats-Validierung selbstsignierter oder automatisch aus TI bezogener Standard-TLS-Zertifikate des CM ist i.d.R. nicht möglich: +

** Per Definition veränderte Host-Angabe in `cn` des TLS-Server-Zertifikts des CM +

** Keine public PKI = keine öffentlich Zertifikatskette, i.d.R. für Betriebssystem unbekannt CAs +
|===

=== TLS-Client-Authentisierung

Das CM unterstützt: 

* *(Empfohlen)* zertifikatsbasierte Client-Authentisierung link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#KOM-LE-A_2181[(mTLS - gemSpec_CM_KOMLE#KOM-LE-A_2181)] +
  ** Bietet höheres Sicherheitsniveau, da auch Client ein Authentisierungsmerkmal im TLS-Handshake angeben muss +
* TLS *ohne* zertifikatsbasierte Client-Authentisierung

Dazu MUSS das PS folgendes unterstützen und in der Reihenfolge priorisieren: +

. *(Empfohlen)* Das PS MUSS TLS mit zertifikatsbasierter Client-Authentisierung unterstützen (*mTLS*) +
.. Das zu nutzende TLS-Client-Zertifikat/die zugrundeliegende Zertifikatsinformation MUSS entweder vom PS bereitgestellt und in das CM importiert, oder vom CM bereitgestellt und in das PS importiert werden können.
. Das PS MUSS TLS ohne zertifikatsbasierte Client-Authentisierung unterstützen.

== Umgang mit Multikonnektor-Umgebungen

Eine KIM-E-Mail-Adresse (Postfach) kann an physische Identitäten/Karten wie SMC-B oder HBA gebunden sein (Regelfall), auf welche über einen TI-Konnektor zugegriffen werden kann. In KIM erfolgt der Zugriff indirekt, über das CM. In Umgebungen in denen mehrere Konntektoren für KIM durch ein CM genutzt werden, MUSS das PS den TI-Konnektor angeben, über welchen der Zugriff auf die zur KIM-E-Mail-Adresse gehördende Karte möglich ist.

* Das PS MUSS dem CM über den Benutzernamen mitteilen, welcher TI-Konnektor genutzt werden soll, siehe dazu Spezifikation KIM-Clientmodul link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#3.3.2.2[SMTP-Benutzername - gemSpec_CM_KOMLE#3.3.2.2] & link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#3.4.2.2[POP3-Benutzername - gemSpec_CM_KOMLE#3.4.2.2]. Die Konfiguration der `KonnektorId` erfolgt im CM.


++++
<p align="left">
  <img width="100%" src=../images/Multikonnektoren.png>
</p>
++++


== Bekannte Probleme und häufige Implementierungsfehler

Nachfolgend werden weitere Aspekte aufgeführt, welche nicht bereits in anderen Abschnitten benannt wurden.

=== Umsetzung der Funktion "E-Mail Weiterleiten"

Das Weiterleiten einer KIM-E-Mail-Nachricht erfordert, dass die Originalnachricht als eigenständiger MIME-Part vom Typ `message/rfc822` (link:https://datatracker.ietf.org/doc/html/rfc2046#section-5.2.1[RFC2046#5.2.1]) in die neu erzeugte Nachricht eingebettet wird. Nur so bleibt die ursprüngliche Nachricht vollständig und unverändert erhalten.

*Beispiel des Aufbau einer weitergeleiteten KIM-E-Mail:*

[source]
----
From: weiterleitender@hrst_domain.kim.telematik
To: empfaenger@andere_domain.kim.telematik
Subject: Fwd: Urspruenglicher Betreff
Message-ID: <neue-eindeutige-id@kim.local>
Date: Wed, 04 Mar 2026 10:00:00 +0100
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="fwd-boundary-001"

--fwd-boundary-001
Content-Type: text/plain; charset=UTF-8

Bitte beachten Sie die weitergeleitete Nachricht im Anhang.

--fwd-boundary-001
Content-Type: message/rfc822
Content-Disposition: inline; filename="weitergeleitet.eml"

From: absender@hrst_domain.kim.telematik
To: ursprung@andere_domain.kim.telematik
Subject: Urspruenglicher Betreff
Message-ID: <originale-message-id@kim.local>
Date: Mon, 02 Mar 2026 08:30:00 +0100
Content-Type: text/plain; charset=UTF-8

[Inhalt der Originalnachricht]

--fwd-boundary-001--
----

*Häufige Fehler beim Weiterleiten:*

* Die Originalnachricht wird unvollständig, als `text/plain`-Bestandteil inline eingefügt, anstatt sie als `message/rfc822`-Teil einzubetten. +
* Beim Weiterleiten wird die `Message-ID` der Originalnachricht in der neuen Nachricht übernommen oder wiederverwendet. Jede neu erzeugte Nachricht MUSS eine eigene, eindeutige `Message-ID` erhalten.
* Das `Content-Disposition` Element des `message/rfc822`-MIME-Parts wird auf `attachment` statt auf `inline` gesetzt, was bei manchen Empfangssystemen zu einer falschen Darstellung führen kann.


=== Verwaltung abgerufener E-Mail-Daten anhand fremder, externer ID´s

_Erläuterung am Beispiel des Identifikators `Message-ID`._

Die `Message-ID` einer E-Mail ist *kein geeignetes Mittel zur eindeutigen Identifikation sowie Verwaltung* abgerufener KIM-E-Mail-Daten im PS

* Die `Message-ID` wird vom sendenden E-Mail-Client erzeugt und liegt damit außerhalb des Einflussbereichs des Empfängers. Sie kann fehlerhaft, leer, uneindeutig oder nicht gemäß *[RFC5322 §3.6.4]* gebildet sein
* Die `Message-ID` kann datenschutzrelevante Informationen enthalten
* Auch andere Fremd-IDs, aus bspw. Header-Elementen, dürfen *nicht als Speicher- oder Referenzschlüssel* verwendet werden, da sie weder eindeutig noch vertrauenswürdig sind.


[width="100%",cols="1a"]
|===
|*Warnung*

* *Entsprechende Verwendung solcher Identifikatoren kann zu schwerwiegenden Fehlern (Kollision) und ggf. Verlust von Daten führen.* +
|===

[width="100%",cols="1a"]
|===
|*Abgrenzung*

Das PS MUSS empfangene Nachrichten im Zusammenhang mit ID´s aus `*POP3 UIDL*` (Unique-ID Listing, gemäß *[RFC1939#7]*) verwalten. Die UIDL wird vom KIM-Fachdienst serverseitig vergeben und ist für die Lebensdauer der Nachricht im Postfach eindeutig und stabil. Die Verwendung von POP3 UIDL ermöglicht es dem PS: +

* bereits abgerufene KIM-E-Mail-Daten zu erkennen und einen erneuten Abruf zu vermeiden, +
* den Abrufstatus je Arbeitsplatz konsistent zu verwalten, +
* Nachrichten sicher zu referenzieren, ohne auf unkontrollierte Absender-Metadaten angewiesen zu sein +
|===




== Übersicht KIM-spezifischer E-Mail-Header-Felder

Die folgende Tabelle gibt eine vollständige Übersicht aller KIM-spezifischen Header-Felder. Detaillierte normative Anforderungen sind in diesem Dokument (<<6.1.2>>), sowie den folgenden Spezifikationen definiert: + 
* link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_FD_KOMLE/latest/[gemSpec_FD_KOMLE] +
* link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/[gemSpec_CM_KOMLE]

[cols="2,1,4",options="header",autowidth]
|===
|Header-Feld |Vom PS zu setzen |Beschreibung

|`X-KIM-Dienstkennung`
|*Ja*
|Kategorisierung der Nachricht. Ohne Angabe setzt das CM den Standardwert. Kann auf der Empfängerseite für Abrufsteuerung sowie automatisierte Verarbeitung verwendet werden. Aktuelle Kennungen: link:https://fachportal.gematik.de/service/dienstkennung-kim-kom-le/[Dienstkennungen KIM - Fachportal gematik]

|`X-KIM-Sendersystem`
|*Ja*
|Name und Version des sendenden Primärsystems. Format: `<Systemname>;<Version>` z.B. `MeinPVS;2.0.0`. Dient der allgemeinem Identifikation des PS-Herstellers.

|`X-KIM-Support`
|*Ja*
|Support-E-Mail-Adresse des PS-Herstellers. Ermöglicht Kontaktaufnahme bei bspw. Fehleranalyse.

|`X-KIM-Middleware`
|*Ja* (bei Middleware)
|Wird von einer zwischengeschalteten Middleware-Komponente gesetzt, sofern eine solche zwischen PS und CM eingesetzt wird. Format: `<Middlewarename>;<Version>` — z.B. `MiddlewareXYZ;2.0.0`

|`X-TI-User-Agent`
|*Ja*
|Übermittlung einer bei der gematik registrierten, eindeutigen Identifikators (client-id/product-id) des PS gemäß (link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_Perf/gemSpec_Perf_V2.75.0/#A_27784[A_27784-* - Senden eines User-Agents (Clientsysteme)])

|`X-KOM-LE-Version`
|Nein
|KOM-LE-Protokollversion der äußeren KOM-LE-Nachricht (z.B. `1.0`, `1.5`). Wird vom sendenden CM gesetzt und vom empfangenden CM ausgewertet. 

|`X-KIM-CMVersion`
|Nein
|Versions-Informationen des sendenden CM, siehe link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/[gemSpec_CM_KOMLE#A_21388-*]

|`X-KIM-PTVersion`
|Nein
|Produkttypversion des sendenden CM, siehe link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/[gemSpec_CM_KOMLE#A_21388-*]

|`X-KIM-KONVersion`
|Nein
|Version des vom Absender verwendeten TI-Konnektors. Gesetzt vom CM des Absenders, siehe link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/[gemSpec_CM_KOMLE#A_21388-*]

|`X-KIM-Auth`
|Nein
|JSON Web Token (JWT) gem. *[RFC7519]* als Authentizitätsnachweis der KIM-E-Mail-Nachricht. Vom CM beim Senden erzeugt und in den inneren Header eingefügt, siehe link:https://gemspec.gematik.de/docs/gemSpec/gemSpec_CM_KOMLE/latest/#A_28582[`Spezifikation X-KIM-Auth`]

|`X-KIM-Fehlermeldung`
|Nein
|Fehlercode, kann mehrfach in einer Fehlernachricht vorkommen. Herstellerspezifische Codes beginnen mit `X` (z.B. `X99`).

|`X-KIM-DecryptionResult`
|Nein
|Ergebnis der Entschlüsselung. `00` = kein Fehler. Andere Codes = Fehler. Gesetzt vom empfangenden CM in der entschlüsselten Nachricht.

|`X-KIM-IntegrityCheckResult`
|Nein
|Ergebnis der Signaturprüfung. `01` = kein Fehler. Andere Codes = Integritätsproblem. Gesetzt vom empfangenden CM. Bei negativem Ergebnis darf den empfangenen Daten *nicht* vertraut werden.

|`X-KIM-KAS-Size`
|Nein
|Größe der entschlüsselten E-Mail-Daten auf dem KAS in Byte. Nur bei Nachrichten >15 MiB (KAS-Nachrichten) vorhanden.

|`X-KIM-KAS-EncSize`
|Nein
|Größe der *verschlüsselten* E-Mail-Daten auf dem KAS in Byte. Nur bei KAS-Nachrichten vorhanden. Wird vom empfangenden CM zur Integritätsprüfung vor dem Download verwendet.
|===

[width="100%",cols="1a"]
|===
|*Hinweis* +

Diese Header-Felder sind nur teilweise in der resultierenden, durch das PS abgerufenen KIM-E-Mail-Nachricht enthalten. Grund ist, dass diese Header-Elemente entweder nicht von einem PS benötigt, ausgewertet werden oder der technische Ablauf diese Header-Elemente nicht erzeugt (bspw. im KAS-Anwendungsfall). Folglich können sich Header-Elemente die über `POP3 TOP` abgerufenen werden, von denen der resultierenden, durch das PS abgerufenen KIM-E-Mail-Nachricht unterscheiden. +
|===
